version: '2.2'

services:

  web:
    image: aspendigital/octobercms:build.428
    init: true
    ports:
      - ${LOCAL_PORT:-80}:80
    environment:
      - TZ=${TZ:-America/Denver}
    volumes:
      - $PWD/.env:/var/www/html/.env
      - $PWD/config/docker:/var/www/html/config/docker
      - $PWD/plugins:/var/www/html/plugins
      - $PWD/storage/app:/var/www/html/storage/app
      - $PWD/storage/logs:/var/www/html/storage/logs
      - $PWD/storage/database.sqlite:/var/www/html/storage/database.sqlite
      - $PWD/themes:/var/www/html/themes

  cron:
    image: aspendigital/octobercms:build.428
    restart: always
    init: true
    command: [sh, -c, "php artisan schedule:run; exec cron -f"]
    environment:
      - TZ=${TZ:-America/Denver}
    volumes_from:
      - web

  worker:
    image: aspendigital/octobercms:build.428
    restart: always
    init: true
    command: "php artisan queue:work redis --daemon --tries=3"
    environment:
      - TZ=${TZ:-America/Denver}
    volumes:
      - $PWD/worker-php.ini:/usr/local/etc/php/conf.d/worker-php.ini
    volumes_from:
      - web

  queue:
    image: redis:4
    restart: always
    init: true
    command: redis-server --tcp-backlog 128 --appendonly yes
    environment:
      - TZ=${TZ:-America/Denver}
    volumes:
      - $PWD/storage/redis:/data
